Count,Message,Traceback,Nodes
22,None,"  File ""/home/paulo/.pyenv/versions/3.9.5/envs/taller3/lib/python3.9/site-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/home/paulo/.pyenv/versions/3.9.5/envs/taller3/lib/python3.9/site-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/paulo/.pyenv/versions/3.9.5/envs/taller3/lib/python3.9/site-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/paulo/taller3/tp1/site_test.py"", line 89, in jobs_seeker
    self.enter_page(""home"")
  File ""/home/paulo/taller3/tp1/site_test.py"", line 77, in enter_page
    self.download_page(page_name)
  File ""/home/paulo/taller3/tp1/site_test.py"", line 48, in download_page
    for asset in assets(html):
  File ""/home/paulo/taller3/tp1/site_test.py"", line 36, in assets
    pq = PyQuery(html)
  File ""/home/paulo/.pyenv/versions/3.9.5/envs/taller3/lib/python3.9/site-packages/pyquery/pyquery.py"", line 228, in __init__
    raise TypeError(context)
",local
12,None,"  File ""/home/paulo/.pyenv/versions/3.9.5/envs/taller3/lib/python3.9/site-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/home/paulo/.pyenv/versions/3.9.5/envs/taller3/lib/python3.9/site-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/paulo/.pyenv/versions/3.9.5/envs/taller3/lib/python3.9/site-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/paulo/taller3/tp1/site_test.py"", line 98, in usual_user
    self.enter_page(""home"")
  File ""/home/paulo/taller3/tp1/site_test.py"", line 77, in enter_page
    self.download_page(page_name)
  File ""/home/paulo/taller3/tp1/site_test.py"", line 48, in download_page
    for asset in assets(html):
  File ""/home/paulo/taller3/tp1/site_test.py"", line 36, in assets
    pq = PyQuery(html)
  File ""/home/paulo/.pyenv/versions/3.9.5/envs/taller3/lib/python3.9/site-packages/pyquery/pyquery.py"", line 228, in __init__
    raise TypeError(context)
",local
